[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base-chain = "http://127.0.0.1:8545"
secondary-chain = "http://127.0.0.1:8546"