FROM ghcr.io/foundry-rs/foundry:v1.2.3

USER root
RUN apt-get update -qq \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq \
 && rm -rf /var/lib/apt/lists/*

USER foundry

WORKDIR /app

CMD ["/bin/bash"] 