[421614]
endpoint_url = "https://arbitrum-sepolia-rpc.publicnode.com"

[560048]
endpoint_url = "https://0xrpc.io/hoodi"

[11155420]
endpoint_url = "https://sepolia.optimism.io"

[1234567890]
endpoint_url = ""
keyRegistry = 560048
votingPowerProvider = [560048]
settlement = [
    421614,
    11155420,
    560048,
]
valSetDriver = 560048
