// Code generated by ogen, DO NOT EDIT.

package relay_api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAggregationProofGet implements GET /getAggregationProof operation.
//
// Get aggregation proof.
//
// GET /getAggregationProof
func (UnimplementedHandler) GetAggregationProofGet(ctx context.Context, params GetAggregationProofGetParams) (r *AggregationProof, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAggregationStatusGet implements GET /getAggregationStatus operation.
//
// Get aggregation status, can be sent only to aggregator nodes.
//
// GET /getAggregationStatus
func (UnimplementedHandler) GetAggregationStatusGet(ctx context.Context, params GetAggregationStatusGetParams) (r *AggregationStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentEpochGet implements GET /getCurrentEpoch operation.
//
// Get current epoch.
//
// GET /getCurrentEpoch
func (UnimplementedHandler) GetCurrentEpochGet(ctx context.Context) (r *GetCurrentEpochGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSignatureRequestGet implements GET /getSignatureRequest operation.
//
// Get signature request by request hash.
//
// GET /getSignatureRequest
func (UnimplementedHandler) GetSignatureRequestGet(ctx context.Context, params GetSignatureRequestGetParams) (r *SignatureRequest, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSignaturesGet implements GET /getSignatures operation.
//
// Get signature by request hash.
//
// GET /getSignatures
func (UnimplementedHandler) GetSignaturesGet(ctx context.Context, params GetSignaturesGetParams) (r []Signature, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSuggestedEpochGet implements GET /getSuggestedEpoch operation.
//
// Get suggested epoch to request sign.
//
// GET /getSuggestedEpoch
func (UnimplementedHandler) GetSuggestedEpochGet(ctx context.Context) (r *GetSuggestedEpochGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetValidatorSetGet implements GET /getValidatorSet operation.
//
// Get current validator set.
//
// GET /getValidatorSet
func (UnimplementedHandler) GetValidatorSetGet(ctx context.Context, params GetValidatorSetGetParams) (r *ValidatorSet, _ error) {
	return r, ht.ErrNotImplemented
}

// SignMessagePost implements POST /signMessage operation.
//
// Sign a message.
//
// POST /signMessage
func (UnimplementedHandler) SignMessagePost(ctx context.Context, req *SignMessagePostReq) (r *SignMessagePostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
