// Code generated by ogen, DO NOT EDIT.

package relay_api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetAggregationProofGetOperation  OperationName = "GetAggregationProofGet"
	GetAggregationStatusGetOperation OperationName = "GetAggregationStatusGet"
	GetCurrentEpochGetOperation      OperationName = "GetCurrentEpochGet"
	GetSignatureRequestGetOperation  OperationName = "GetSignatureRequestGet"
	GetSignaturesGetOperation        OperationName = "GetSignaturesGet"
	GetSuggestedEpochGetOperation    OperationName = "GetSuggestedEpochGet"
	GetValidatorSetGetOperation      OperationName = "GetValidatorSetGet"
	SignMessagePostOperation         OperationName = "SignMessagePost"
)
